# Generated by Django 4.2.30 on 2026-05-25 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid phone number.')]),
        ),
    ]
