# Generated by Django 4.2.30 on 2026-05-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_level',
            field=models.CharField(choices=[('Standard', 'Standard (Economy)'), ('Express', 'Express Road (Fast)'), ('Priority', 'Priority Air (Next-Day)')], default='Standard', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='width',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='TransitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=180)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portal.shipment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
